AarhusWebDev/AarhusWebDev/ViewModels/ContactForm.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace AarhusWebDev.ViewModels
{
    public class ContactForm
    {
        [Required]
        public string Name { get; set; }
        [Required]
        [EmailAddress(ErrorMessage = "This is not a valid email address")]
        public string Email { get; set; }
        [Required]
        public string Subject { get; set; }
        [Required]
        public string Message { get; set; }
    }
}

AarhusWebDev/AarhusWebDev/Controllers/ContactFormSurfaceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Mail;
using System.Web;
using System.Web.Mvc;
using Umbraco.Web.Mvc;
using AarhusWebDev.ViewModels;
using Umbraco.Core.Models;

namespace AarhusWebDev.Controllers
{
    public class ContactFormSurfaceController : SurfaceController
    {
        public ActionResult Index()
        {
            return PartialView("ContactForm", new ContactForm());
        }

        [HttpPost]
        public ActionResult HandleFormSubmit(ContactForm model)
        {
            if (!ModelState.IsValid)
            {
                return CurrentUmbracoPage();
            }
            {
                // sender mail
                MailMessage message = new MailMessage();
                message.To.Add("smonchristensen17@gmail.com");
                message.Subject = model.Subject;
                message.From = new MailAddress(model.Email, model.Name);
                message.Body = model.Message + "\n my email is: " + model.Email;
                
                TempData["success"] = true;

                IContent comment = Services.ContentService.CreateContent(model.Subject, CurrentPage.Id, "Comments");

                comment.SetValue("name", model.Name);
                comment.SetValue("email", model.Email);
                comment.SetValue("subject", model.Subject);
                comment.SetValue("message", model.Message);

                // Save
                Services.ContentService.Save(comment);

                //Save and publish
                //Services.ContentService.SaveAndPublishWithStatus(comment);

                return RedirectToCurrentUmbracoPage();
            }

            

        }
    }
}

AarhusWebDev/AarhusWebDev/Views/ArticlesItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<h1>@Umbraco.Field("articlesTitle")</h1>
	<p>@Umbraco.Field("articlesContent")</p>

AarhusWebDev/AarhusWebDev/Views/ArticlesMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

<h1>@Umbraco.Field("articlesTitle")</h1>
<p>@Umbraco.Field("articlesContent")</p>


@Umbraco.RenderMacro("listArticles")

AarhusWebDev/AarhusWebDev/Views/Comments.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

AarhusWebDev/AarhusWebDev/Views/ContactPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@Umbraco.Field("contactPageTitle")
@Umbraco.Field("contactPageContent")
	
@Html.Action("Index", "ContactFormSurface")

AarhusWebDev/AarhusWebDev/Views/HomePage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@Umbraco.Field("pageTitle")
@Umbraco.Field("pageContent")
	
@Umbraco.RenderMacro("CompletedProjects")

AarhusWebDev/AarhusWebDev/Views/MacroPartials/CompletedProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

@{
    var page = Umbraco.Content(1072).Children.OrderBy("createDate descending");
	var i = 0;
}

<h3>2 latest completed projects</h3>


@foreach (var child in page) {
        if(child.projectStatus == ("Completed") && i < 2){
			i++;
            <li>
                <a href="@child.Url">@child.Name</a>
                <a href="@child.Url">@child.CreateDate</a>
            </li>
        }
}

AarhusWebDev/AarhusWebDev/Views/MacroPartials/TopMenu.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
<nav class="navbar navbar-default navbar-fixed-top navbar-inverse">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
			<a class="navbar-brand" href="#">AarhusWebDevCoop</a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <div class="container">
		<ul class="nav navbar-nav">
        @{
            var maxLevelForNav = 4;            
            var home = CurrentPage.AncestorsOrSelf(1).First();

            @RenderNavForNode(home, 1)

            foreach (var page in home.Children.Where("Visible"))
            {
                @RenderNavForNode(page, maxLevelForNav);
            }
        }
    	</ul>
		</div>
	
        </div>
      </div>
    </nav>

@helper RenderNavForNode(dynamic page, int maxLevel)
{
    var current = CurrentPage.Id == page.Id ? "active" : null;
    
	if (page.Children.Where("Visible").Any() && page.Level == 2)
	{
		@:<li class="dropdown @current"><a href="@page.Url" class="dropdown-toggle @current" data-toggle="dropdown" role="button" aria-expanded="false">@page.Name<span class="caret"></span></a>
	}
	
	else if (page.Children.Where("Visible").Any() && page.Level > 2)
	{
		@:<li class="dropdown-submenu @current"><a class="@current" href="@page.Url">@page.Name</a>
	}
	else
	{
		@:<li><a class="@current" href="@page.Url">@page.Name</a></li>
	}
	
	
    if (page.Children.Where("Visible").Any() && page.Level < maxLevel)
    {
		
        <ul class="dropdown-menu" role="menu">
            @foreach (var subPage in page.Children.Where("Visible"))
            {
				
                @RenderNavForNode(subPage, maxLevel)
            }
        </ul>
    }
	
	
}

AarhusWebDev/AarhusWebDev/Views/MacroPartials/generateMembers.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
@{
var memberService =
ApplicationContext.Current.Services.MemberService;

var members = memberService.GetMembersByGroup("Active");
}

<h1>Active members</h1>

@foreach (var member in members) 
{
<p>
@(member.GetValue("firstname") + " "
+ member.GetValue("lastname")) <br/>
@member.GetValue("adress")<br />
@(member.GetValue("zip") + " "
+ member.GetValue("city"))<br />
Mobile: @member.GetValue("mobile")<br />
</p>
}

AarhusWebDev/AarhusWebDev/Views/MacroPartials/generateProspectMembers.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage
	
@{
var memberService =
ApplicationContext.Current.Services.MemberService;

var prospectMembers = memberService.GetMembersByGroup("Prospect");
}

<h1>Prospect members</h1>

@foreach (var member in prospectMembers) 
{
<p>
@(member.GetValue("firstname") + " "
+ member.GetValue("lastname"))
</p>
}

AarhusWebDev/AarhusWebDev/Views/MacroPartials/listArticles.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage


@{ var selection = Umbraco.Content(1067).Children; }
@* OrderBy() takes the property to sort by and optionally order desc/asc *@


@foreach (var item in selection)
{
	<a href="@item.Url">@item.Name</a>
	@Umbraco.Truncate(@item.ArticlesContent,300) <a href="@item.Url">Read More..</a>
	<hr>
}

AarhusWebDev/AarhusWebDev/Views/MacroPartials/listProjects.cshtml
@inherits Umbraco.Web.Macros.PartialViewMacroPage

	@{ var selection = Umbraco.Content(1072).Children;
	 }
@* OrderBy() takes the property to sort by *@

<table class="table table-bordered">
	<tr>
		<th>Title</th>
		<th>Status</th>
	</tr>
    @foreach (var item in selection)
    {
		<tr>
			<td>
				<a href="@item.Url">@item.Name</a>
			</td>
			<td>
				@item.projectStatus
			</td>
		</tr>
    }
</table>

AarhusWebDev/AarhusWebDev/Views/Master.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<html>
	<head>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
		
  	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="/css/sticky-footer-navbar.css">
  	<script src="https://code.jquery.com/jquery-2.1.4.min.js"></script>
    <script src="~/Scripts/jquery.validate.min.js"></script>
    <script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
	</head>
	<body>
		

	@Umbraco.RenderMacro("TopMenu")
<div class="container">
	
	
@RenderBody()
</div>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>

</body>
</html>

AarhusWebDev/AarhusWebDev/Views/Members.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@Umbraco.RenderMacro("generateMembers")
	
@Umbraco.RenderMacro("generateProspectMembers")

AarhusWebDev/AarhusWebDev/Views/Partials/ContactForm.cshtml
@model AarhusWebDev.ViewModels.ContactForm
@{
    Layout = null;
}
@using System.ComponentModel.DataAnnotations;
@if (TempData["success"] == null)
{
    using (Html.BeginUmbracoForm("HandleFormSubmit", "ContactFormSurface", new object { }, new { @class = "form-horizontal" }))
    {
        <div class="form-group">
            @Html.LabelFor(m => m.Name, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Name, new { @class = "form-control", placeholder = "Name" })
                @Html.ValidationMessageFor(m => m.Name)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Email, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Email, new { @class = "form-control", placeholder = "Email" })
                @Html.ValidationMessageFor(m => m.Email)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Subject, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Subject, new { @class = "form-control", placeholder = "Subject" })
                @Html.ValidationMessageFor(m => m.Subject)
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(m => m.Message, new { @class = "col-sm-2 control-label" })
            <div class="col-sm-6">
                @Html.TextBoxFor(m => m.Message, new { @class = "form-control", placeholder = "Message" })
                @Html.ValidationMessageFor(m => m.Message)
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-6">
                <button id="contact-submit" type="submit" class="btn btn-primary input-medium pull-left">Send</button>
            </div>
        </div>
    }
}
else
{
    <p>Thank you for contacting us. We’ll be in touch soon!</p>
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Bootstrap2.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="@("span" + s.grid) column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="@("span" + area.grid) column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Bootstrap3.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates
@using Newtonsoft.Json.Linq

@* 
    Razor helpers located at the bottom of this file
*@

@if (Model != null && Model.sections != null)
{
    var oneColumn = ((System.Collections.ICollection)Model.sections).Count == 1;
    
    <div class="umb-grid">
        @if (oneColumn)
        {
            foreach (var section in Model.sections) {
                <div class="grid-section">
                    @foreach (var row in section.rows) {
                        @renderRow(row, true);
                    }
                </div>
            }   
        }else { 
            <div class="container">
                <div class="row clearfix">
                    @foreach (var s in Model.sections) {
                        <div class="grid-section">
                            <div class="col-md-@s.grid column">
                                @foreach (var row in s.rows) {
                                    @renderRow(row, false);
                                }
                            </div>
                        </div>
                    }
                </div>
            </div>   
        }
    </div>
}

@helper renderRow(dynamic row, bool singleColumn){
    <div @RenderElementAttributes(row)>
        @Umbraco.If(singleColumn, "<div class='container'>")
        <div class="row clearfix">
            @foreach ( var area in row.areas ) {
            <div class="col-md-@area.grid column">
                <div @RenderElementAttributes(area)>
                    @foreach (var control in area.controls) {
                        if (control !=null && control.editor != null && control.editor.view != null ) {
                            <text>@Html.Partial("grid/editors/base", (object)control)</text>
                        }
                    }
                </div>
            </div>}
        </div>
        @Umbraco.If(singleColumn, "</div>")
    </div>
}

@functions {
    public static MvcHtmlString RenderElementAttributes(dynamic contentItem)
    {
        var attrs = new List<string>();
        JObject cfg = contentItem.config;

        if(cfg != null)
            foreach (JProperty property in cfg.Properties()) {
                attrs.Add(property.Name + "=\"" + property.Value.ToString() + "\"");
            }
                
        JObject style = contentItem.styles;

        if (style != null) { 
        var cssVals = new List<string>();
        foreach (JProperty property in style.Properties())
            cssVals.Add(property.Name + ":" + property.Value.ToString() + ";");

        if (cssVals.Any())
            attrs.Add("style=\"" + string.Join(" ", cssVals) + "\"");
        }
            
        return new MvcHtmlString(string.Join(" ", attrs));
    }
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Base.cshtml
@model dynamic
@using Umbraco.Web.Templates

@functions {
    public static string EditorView(dynamic contentItem)
    {
        string view = contentItem.editor.render != null ? contentItem.editor.render.ToString() : contentItem.editor.view.ToString();
        view = view.ToLower().Replace(".html", ".cshtml");
        
        if (!view.Contains("/")) {
            view = "grid/editors/" + view;
        }

        return view;
    }
}
@try
{
    string editor = EditorView(Model);                                                       
    <text>@Html.Partial(editor, (object)Model)</text>
}
catch (Exception ex) { 
<pre>@ex.ToString()</pre>
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Embed.cshtml
@model dynamic
@using Umbraco.Web.Templates
@Html.Raw(Model.value)

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Macro.cshtml
@inherits UmbracoViewPage<dynamic>
@using Umbraco.Web.Templates


@if (Model.value != null)
{
    string macroAlias = Model.value.macroAlias.ToString();
    ViewDataDictionary parameters = new ViewDataDictionary();
    foreach (dynamic mpd in Model.value.macroParamsDictionary)
    {
        parameters.Add(mpd.Name, mpd.Value);
    }

    <text>
        @Umbraco.RenderMacro(macroAlias, parameters)
    </text>
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Media.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.value != null)
{   
    var url = Model.value.image;
    if(Model.editor.config != null && Model.editor.config.size != null){
        url += "?width=" + Model.editor.config.size.width;
        url += "&height=" + Model.editor.config.size.height;

        if(Model.value.focalPoint != null){
            url += "&center=" + Model.value.focalPoint.top +"," + Model.value.focalPoint.left;
            url += "&mode=crop";
        }
    }
    
    <img src="@url" alt="@Model.value.caption">
    
    if (Model.value.caption != null)
    {
        <p class="caption">@Model.value.caption</p>
    }
}

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Rte.cshtml
@model dynamic
@using Umbraco.Web.Templates

@Html.Raw(TemplateUtilities.ParseInternalLinks(Model.value.ToString()))

AarhusWebDev/AarhusWebDev/Views/Partials/Grid/Editors/Textstring.cshtml
@model dynamic
@using Umbraco.Web.Templates

@if (Model.editor.config.markup != null)
{
    string markup = Model.editor.config.markup.ToString();

    markup = markup.Replace("#value#", Model.value.ToString());
    markup = markup.Replace("#style#", Model.editor.config.style.ToString());

    <text>
        @Html.Raw(markup)
    </text>
}
else
{
    <text>
        <div style="@Model.editor.config.style">@Model.value</div>
    </text>
}

AarhusWebDev/AarhusWebDev/Views/Partials/login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage


@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers

@{
    var loginModel = new LoginModel();
    
    Html.EnableClientValidation();
    Html.EnableUnobtrusiveJavaScript();
    Html.RequiresJs("/umbraco_client/ui/jquery.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
    Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");
}

@* NOTE: This RenderJsHere code should be put on your main template page where the rest of your script tags are placed *@
@Html.RenderJsHere()

@using (Html.BeginUmbracoForm<UmbLoginController>("HandleLogin"))
{
    <fieldset>
        <legend>Login</legend>
        
        @Html.ValidationSummary("login", true)

        @Html.LabelFor(m => loginModel.Username)
        @Html.TextBoxFor(m => loginModel.Username)
        @Html.ValidationMessageFor(m => loginModel.Username)
        <br />

        @Html.LabelFor(m => loginModel.Password)
        @Html.PasswordFor(m => loginModel.Password)
        @Html.ValidationMessageFor(m => loginModel.Password)
        <br />

        <button>Login</button>
    </fieldset>  
}

AarhusWebDev/AarhusWebDev/Views/Partials/logout.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using System.Web.Mvc.Html
@using ClientDependency.Core.Mvc
@using Umbraco.Web
@using Umbraco.Web.Models
@using Umbraco.Web.Controllers
@{

var loginStatusModel = Members.GetCurrentLoginStatus();

Html.EnableClientValidation();
Html.EnableUnobtrusiveJavaScript();
Html.RequiresJs("/umbraco_client/ui/jquery.js");
Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.min.js");
Html.RequiresJs("/umbraco_client/Application/JQuery/jquery.validate.unobtrusive.min.js");

var logoutModel = new PostRedirectModel();
logoutModel.RedirectUrl = "/";

}

@Html.RenderJsHere()
@if (loginStatusModel.IsLoggedIn)
{

<p>You are currently logged in as @loginStatusModel.Name</p>


using (Html.BeginUmbracoForm<UmbLoginStatusController>("HandleLogout"))
{
    <fieldset>
        <legendend>Logout</legendend>
        <button>Logout</button>
    </fieldset>
    
    @Html.HiddenFor(m => logoutModel.RedirectUrl)
    }
}

AarhusWebDev/AarhusWebDev/Views/ProjectsItem.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}

@Umbraco.Field("projectTitle")

<br>

@Umbraco.Field("projectContent")
	

AarhusWebDev/AarhusWebDev/Views/ProjectsMain.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}


<h1>@Umbraco.Field("projectTitle")</h1>
<p>@Umbraco.Field("projectContent")</p>


@Umbraco.RenderMacro("listProjects")

AarhusWebDev/AarhusWebDev/Views/TextPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@Umbraco.Field("textPageTitle")
@Umbraco.Field("textPageContent")

@CurrentPage.GetGridHtml("frontpageArticle")

AarhusWebDev/AarhusWebDev/Views/login.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "Master.cshtml";
}
@if(!Members.GetCurrentLoginStatus().IsLoggedIn){
	@Html.Partial("login");
}else{
	<p>
		@Html.Partial("logout");	
	</p>
}